import type { HueSeed, Oklch, ThemeInputs } from "./types.js";
import { buildRamps } from "./ramps.js";
import { buildAlphas } from "./derived.js";
import { resolveSemantics } from "./semantics.js";
import { BRAND_DEFAULT_L } from "./steps.js";

export const BANNER = "auto-generated by build:theme — do not edit";

export function oklchToDtcg(c: Oklch): object {
  const value: Record<string, unknown> = {
    colorSpace: "oklch",
    components: [round(c.l), round(c.c), round(c.h, 2)],
  };
  if (c.alpha !== undefined) value.alpha = c.alpha;
  return { $type: "color", $value: value };
}

function round(n: number, dp = 4): number {
  const f = 10 ** dp;
  return Math.round(n * f) / f;
}

const rampNamePrefix: Record<string, string> = {
  neutral: "color-neutral",
  accent: "color-accent",
  secondary: "color-secondary",
  tertiary: "color-tertiary",
  success: "color-success",
  error: "color-error",
  warning: "color-warning",
  info: "color-info",
};

export function buildPrimitivesDtcg(inputs: ThemeInputs): Record<string, object> {
  const out: Record<string, object> = {};
  const ramps = buildRamps(inputs);
  for (const [key, prefix] of Object.entries(rampNamePrefix)) {
    const ramp = ramps[key as keyof typeof ramps];
    for (const [step, color] of Object.entries(ramp)) {
      out[`${prefix}-${step}`] = oklchToDtcg(color);
    }
  }
  const { black, white } = buildAlphas();
  for (const [step, color] of Object.entries(black)) out[`color-black-alpha-${step}`] = oklchToDtcg(color);
  for (const [step, color] of Object.entries(white)) out[`color-white-alpha-${step}`] = oklchToDtcg(color);

  for (const [step, color] of Object.entries(ramps.darkSurface)) {
    out[`color-neutral-dark-surface-${step}`] = oklchToDtcg(color);
  }

  const slots: ["primary" | "secondary" | "tertiary", HueSeed][] = [
    ["primary", inputs.accents.primary],
    ["secondary", inputs.accents.secondary],
    ["tertiary", inputs.accents.tertiary],
  ];
  for (const [slot, seed] of slots) {
    const brand = inputs.brand?.[slot] ?? { l: BRAND_DEFAULT_L, c: seed.chroma, h: seed.hue };
    out[`color-brand-${slot}`] = oklchToDtcg(brand);
  }
  return out;
}

export function buildSemanticDtcg(inputs: ThemeInputs, mode: "light" | "dark"): Record<string, any> {
  const ramps = buildRamps(inputs);
  const resolved = resolveSemantics(ramps, inputs, mode);
  const out: Record<string, any> = {};
  for (const [name, token] of Object.entries(resolved)) {
    if ("ref" in token) out[name] = { $type: "color", $value: `{${token.ref}}` };
    else out[name] = token.raw;
  }
  return out;
}

export function buildGeneratedFiles(inputs: ThemeInputs): Record<string, object> {
  const withBanner = (obj: object) => ({ $description: BANNER, ...obj });
  return {
    "primitives-color.mode-1.tokens.json": withBanner(buildPrimitivesDtcg(inputs)),
    "color.light.tokens.json": withBanner(buildSemanticDtcg(inputs, "light")),
    "color.dark.tokens.json": withBanner(buildSemanticDtcg(inputs, "dark")),
  };
}
