import type { HueSeed, Oklch, ThemeInputs } from "./types.js";
import { buildRamps } from "./ramps.js";
import { buildAlphas } from "./derived.js";
import { resolveSemantics } from "./semantics.js";
import { BRAND_DEFAULT_L } from "./steps.js";

export const BANNER = "auto-generated by build:theme — do not edit";

export function oklchToDtcg(c: Oklch): object {
  const value: Record<string, unknown> = {
    colorSpace: "oklch",
    components: [round(c.l), round(c.c), round(c.h, 2)],
  };
  if (c.alpha !== undefined) value.alpha = c.alpha;
  return { $type: "color", $value: value };
}

function round(n: number, dp = 4): number {
  const f = 10 ** dp;
  return Math.round(n * f) / f;
}

const rampNamePrefix: Record<string, string> = {
  neutral: "color-neutral",
  accent: "color-accent",
  secondary: "color-secondary",
  tertiary: "color-tertiary",
  success: "color-success",
  error: "color-error",
  warning: "color-warning",
  info: "color-info",
};

export function buildPrimitivesDtcg(inputs: ThemeInputs): Record<string, object> {
  const out: Record<string, object> = {};
  const ramps = buildRamps(inputs);
  for (const [key, prefix] of Object.entries(rampNamePrefix)) {
    const ramp = ramps[key as keyof typeof ramps];
    for (const [step, color] of Object.entries(ramp)) {
      out[`${prefix}-${step}`] = oklchToDtcg(color);
    }
  }
  const { black, white } = buildAlphas();
  for (const [step, color] of Object.entries(black)) out[`color-black-alpha-${step}`] = oklchToDtcg(color);
  for (const [step, color] of Object.entries(white)) out[`color-white-alpha-${step}`] = oklchToDtcg(color);

  for (const [step, color] of Object.entries(ramps.darkSurface)) {
    out[`color-neutral-dark-surface-${step}`] = oklchToDtcg(color);
  }

  const slots: ["primary" | "secondary" | "tertiary", HueSeed][] = [
    ["primary", inputs.accents.primary],
    ["secondary", inputs.accents.secondary],
    ["tertiary", inputs.accents.tertiary],
  ];
  for (const [slot, seed] of slots) {
    const brand = inputs.brand?.[slot] ?? { l: BRAND_DEFAULT_L, c: seed.chroma, h: seed.hue };
    out[`color-brand-${slot}`] = oklchToDtcg(brand);
  }
  return out;
}

export function buildSemanticDtcg(inputs: ThemeInputs, mode: "light" | "dark"): Record<string, any> {
  const ramps = buildRamps(inputs);
  const resolved = resolveSemantics(ramps, inputs, mode);
  const out: Record<string, any> = {};
  for (const [name, token] of Object.entries(resolved)) {
    if ("ref" in token) out[name] = { $type: "color", $value: `{${token.ref}}` };
    else out[name] = token.raw;
  }
  return out;
}

// Static primitive tokens from src/tokens/primitives-color.static.tokens.json.
// They are not generated by buildPrimitivesDtcg (intentionally — they are
// design-time constants, not computed from ThemeInputs), but semantic
// passthrough tokens (color-retro-*, color-circled-marker) reference them.
// Merging them here ensures buildGeneratedFiles produces a self-contained bundle
// where every semantic {ref} resolves.
const STATIC_COLOR_PRIMITIVES: Record<string, object> = {
  "color-prism-green": {
    $type: "color",
    $value: { colorSpace: "srgb", components: [0.16470588743686676, 0.5960784554481506, 0.16862745583057404] },
  },
  "color-prism-yellow": {
    $type: "color",
    $value: { colorSpace: "srgb", components: [1, 0.7607843279838562, 0.054901961237192154] },
  },
  "color-prism-orange": {
    $type: "color",
    $value: { colorSpace: "srgb", components: [1, 0.5490196347236633, 0] },
  },
  "color-prism-red": {
    $type: "color",
    $value: {
      colorSpace: "srgb",
      components: [0.9843137264251709, 0.14509804546833038, 0.007843137718737125],
    },
  },
  "color-prism-magenta": {
    $type: "color",
    $value: { colorSpace: "srgb", components: [0.7450980544090271, 0.03921568766236305, 0.47843137383461] },
  },
  "color-prism-purple": {
    $type: "color",
    $value: { colorSpace: "srgb", components: [0.46666666865348816, 0.12156862765550613, 0.7215686440467834] },
  },
  "color-prism-blue": {
    $type: "color",
    $value: { colorSpace: "srgb", components: [0.01568627543747425, 0.32156863808631897, 0.7490196228027344] },
  },
  "color-prism-cyan": {
    $type: "color",
    $value: { colorSpace: "srgb", components: [0.08235294371843338, 0.6941176652908325, 0.8196078538894653] },
  },
};

export function buildGeneratedFiles(inputs: ThemeInputs): Record<string, object> {
  const withBanner = (obj: object) => ({ $description: BANNER, ...obj });
  return {
    "primitives-color.mode-1.tokens.json": withBanner({
      ...buildPrimitivesDtcg(inputs),
      ...STATIC_COLOR_PRIMITIVES,
    }),
    "color.light.tokens.json": withBanner(buildSemanticDtcg(inputs, "light")),
    "color.dark.tokens.json": withBanner(buildSemanticDtcg(inputs, "dark")),
  };
}
