import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { HueSeed, Oklch, ThemeInputs } from "./types.js";
import { buildRamps } from "./ramps.js";
import { buildAlphas, buildDarkSurfaces } from "./derived.js";
import { resolveSemantics } from "./semantics.js";
import { BRAND_DEFAULT_L } from "./steps.js";

const BANNER = "auto-generated by build:theme — do not edit";

export function oklchToDtcg(c: Oklch): object {
  const value: Record<string, unknown> = {
    colorSpace: "oklch",
    components: [round(c.l), round(c.c), round(c.h, 2)],
  };
  if (c.alpha !== undefined) value.alpha = c.alpha;
  return { $type: "color", $value: value };
}

function round(n: number, dp = 4): number {
  const f = 10 ** dp;
  return Math.round(n * f) / f;
}

const rampNamePrefix: Record<string, string> = {
  neutral: "color-neutral",
  accent: "color-accent",
  secondary: "color-secondary",
  tertiary: "color-tertiary",
  success: "color-success",
  error: "color-error",
  warning: "color-warning",
  info: "color-info",
};

export function buildPrimitivesDtcg(inputs: ThemeInputs): Record<string, object> {
  const out: Record<string, object> = {};
  const ramps = buildRamps(inputs);
  for (const [key, prefix] of Object.entries(rampNamePrefix)) {
    const ramp = ramps[key as keyof typeof ramps];
    for (const [step, color] of Object.entries(ramp)) {
      out[`${prefix}-${step}`] = oklchToDtcg(color);
    }
  }
  const { black, white } = buildAlphas();
  for (const [step, color] of Object.entries(black)) out[`color-black-alpha-${step}`] = oklchToDtcg(color);
  for (const [step, color] of Object.entries(white)) out[`color-white-alpha-${step}`] = oklchToDtcg(color);

  const darkSurf = buildDarkSurfaces(inputs.neutral.hue, inputs.neutral.chroma);
  for (const [step, color] of Object.entries(darkSurf)) {
    out[`color-neutral-dark-surface-${step}`] = oklchToDtcg(color);
  }

  // Verbatim brand colors per accent slot. Uses the supplied exact color when
  // present, else the accent's hue/chroma at a representative lightness.
  const slots: ["primary" | "secondary" | "tertiary", HueSeed][] = [
    ["primary", inputs.accents.primary],
    ["secondary", inputs.accents.secondary],
    ["tertiary", inputs.accents.tertiary],
  ];
  for (const [slot, seed] of slots) {
    const brand = inputs.brand?.[slot] ?? { l: BRAND_DEFAULT_L, c: seed.chroma, h: seed.hue };
    out[`color-brand-${slot}`] = oklchToDtcg(brand);
  }
  return out;
}

export function buildSemanticDtcg(inputs: ThemeInputs, mode: "light" | "dark"): Record<string, any> {
  const ramps = buildRamps(inputs);
  const resolved = resolveSemantics(ramps, inputs, mode);
  const out: Record<string, any> = {};
  for (const [name, token] of Object.entries(resolved)) {
    if ("ref" in token) out[name] = { $type: "color", $value: `{${token.ref}}` };
    else out[name] = token.raw;          // emit the literal DTCG token (e.g. state dimension tokens) verbatim
  }
  return out;
}

export function writeGeneratedTokens(inputs: ThemeInputs, tokensDir: string): void {
  mkdirSync(tokensDir, { recursive: true });
  const withBanner = (obj: object) => ({ $description: BANNER, ...obj });

  writeFileSync(
    join(tokensDir, "primitives-color.mode-1.tokens.json"),
    JSON.stringify(withBanner(buildPrimitivesDtcg(inputs)), null, 2) + "\n",
  );
  writeFileSync(
    join(tokensDir, "color.light.tokens.json"),
    JSON.stringify(withBanner(buildSemanticDtcg(inputs, "light")), null, 2) + "\n",
  );
  writeFileSync(
    join(tokensDir, "color.dark.tokens.json"),
    JSON.stringify(withBanner(buildSemanticDtcg(inputs, "dark")), null, 2) + "\n",
  );
}
